import Head from "next/head";

const SEO = () => {
  return (
    <Head>
      <title>Next Fire</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default SEO;
